### ISSUE TITLE
User can create an account

### ISSUE THREAD

**Issue by sal-garcia** [sal-garcia/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to create an account
user will be able to insert information about him such as his name and the instrument he plays etc
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to access the account that they created and view his information along with other accounts made by other users
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (23)](https://user-images.githubusercontent.com/51901536/177900705-aa1bc210-afac-4621-bc6a-3078c6bf2708.png)
![Screenshot (22)](https://user-images.githubusercontent.com/51901536/177901298-e185b91d-ba52-4ad9-842b-4b062f158423.png)
![Screenshot (27)](https://user-images.githubusercontent.com/51901536/177902218-2198f2f1-9844-43c3-985d-ba9b3431e4fa.png)
![Screenshot (26)](https://user-images.githubusercontent.com/51901536/177902224-5677c542-feab-4064-9ade-8f06bf4be7c1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to Create create users table 
- [x] Update `schema.sql` to Create create comments table
- [x] Update `data.sql` to to include the username
- [x] Update `data.sql` to to include the instrument
- [x] Update `data.sql` to to include the location
- [x] Update `data.sql` to to include the about user info

### ☁️ Server

- [x] Update `server/index.js` to include error handling if any of the input fields are not filled in
- [x] Update `server/index.js` to include error handling if any of the input fields are filled in with the wrong values
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the log in section
- [x] Update component to change when the log in section has been submitted 
- [x] Create a component to display the account creation section
- [x] Update component to change when the account information section has been submitted 

### 🧑‍⚕️ Clean Up
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
