### ISSUE TITLE
Feature: User can search for musicians by instrument

### ISSUE THREAD

**Issue by sal-garcia** [sal-garcia/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

users will be able to find others users that play the desired instrument
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to select what instrument he desires to look for and the he will be able to view and select all of the musicians that play that instrument
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (31)](https://user-images.githubusercontent.com/51901536/177914281-0a48e4b8-4d1d-416d-8f73-c67fe2b566e8.png)
![Screenshot (30)](https://user-images.githubusercontent.com/51901536/177914294-f6e84eb9-bd9d-479f-ba5a-f3192c8e1a66.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to create users table
- [ ] Update `data.sql` to include all of the different types of instruments in that area

### ⚡ Client

- [ ] Create a component to display all of the musicians available in that area
- [ ] Update component to change when a musician is added to a location or when the user clicks on a musician 

### 🧑‍⚕️ Clean Up

 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
